# Generated by Django 3.0 on 2022-03-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
